# Machine Learning Notes & Practice

这个 Notebook 用于配合 USC EE559《Machine Learning》的学习。

课程主要从统计学习与数学推导的角度介绍机器学习，为了配合计算机与机器学习工程相关工作。因此，希望通过这个 Notebook 将课程中的理论、代码实现和工程理解结合起来。

目标不是只会推公式，也不是只会调用库，而是能够理解原理、实现算法，并用清晰易懂的语言解释机器学习模型。

## 1. 线性回归（Linear Regression）

线性回归是机器学习中最基础的监督学习模型之一。

它的目标是找到输入特征与输出变量之间的线性关系，并利用这种关系进行预测。

在统计学中，线性回归通常被视为参数估计问题；在机器学习中，线性回归通常被视为最小化预测误差的优化问题。

本节将从直观理解、数学推导、代码实现以及工程视角四个方面进行学习。

## 1.1 为什么要学习线性回归？

虽然现实世界中的问题往往比线性关系复杂得多，但线性回归包含了机器学习中最核心的思想：**建模（Modeling）、损失函数（Loss Function）和参数学习（Learning Parameters）**。

---

### 统计学视角

#### 是什么？

统计学认为数据是由某种真实规律产生的：

$$
y = X\beta + \epsilon
$$

其中：

- $X$ 为观测到的特征（Features）
- $\beta$ 为真实但未知的参数（Parameters）
- $\epsilon$ 为随机误差（Error Term）

线性回归本质上是一个 **参数估计问题（Parameter Estimation Problem）**。

---

#### 为什么学习？

统计学不仅希望预测结果，更希望解释数据背后的规律。
统计学关注的不仅是预测，更是变量之间的关系以及结论是否可靠。

---

#### 怎么解决？

通过样本数据估计未知参数：

$$
\hat{\beta}
$$

最经典的方法是 Ordinary Least Squares（OLS，普通最小二乘法）。

其核心思想是：寻找一组参数，使模型预测值与真实值之间的误差尽可能小。

具体来说，就是最小化残差平方和（Residual Sum of Squares, RSS）：

$$
RSS = \sum_{i=1}^{n}(y_i-\hat{y}_i)^2
$$

对于线性回归，最终可以得到解析解（Closed-form Solution）：

$$
\hat{\beta}
=
(X^TX)^{-1}X^Ty
$$

---

### 机器学习 / 工程视角

#### 是什么？

机器学习把线性回归看成一个预测模型：

$$
\hat{y} = w^T x + b
$$

输入特征后输出预测值。

---

#### 为什么学习？

线性回归虽然简单，但已经包含了现代机器学习训练流程中的核心组件：
后面的 Logistic Regression、Neural Network、Transformer 本质上都在重复这一套流程。

---

#### 怎么解决？

先定义模型：

$$
\hat{y}=w^Tx+b
$$

再定义损失函数：

$$
MSE=\frac1n\sum_{i=1}^{n}(y_i-\hat{y}_i)^2
$$

最后通过优化算法寻找最优参数：

$$
w,b
$$

常见方法：

- Closed-form Solution（正规方程）
- Gradient Descent（梯度下降）
- SGD（随机梯度下降）
- Adam

---

### 因此

统计学派更关注：

> 数据为什么会这样产生？

机器学习派更关注：

> 如何利用数据做出更好的预测？

前者强调解释（Interpretation），后者强调预测（Prediction）。

两者研究的是同一个模型，但关注的问题不同。

## 1.2 如何得到最优参数？

虽然统计学和机器学习最终都在寻找一组最优参数，但两者的思考方式并不相同。

---

### 统计学：OLS（Ordinary Least Squares）

统计学认为模型满足：

$$
y = X\beta + \epsilon
$$

目标是估计未知参数：

$$
\beta
$$

OLS 的思想是寻找一组参数，使残差平方和（RSS）最小：

$$
RSS = \sum_{i=1}^{n}(y_i-\hat y_i)^2
$$

将 RSS 对参数求导，并令导数为 0：

$$
\frac{\partial RSS}{\partial \beta}=0
$$

最终得到解析解（Normal Equation）：

$$
\hat{\beta}
=
(X^T X)^{-1}X^T y
$$

特点：

* 一步直接算出答案
* 不需要迭代
* 可以分析估计量的统计性质
* 当特征维度很高时计算成本较大

---

#### OLS 的思维方式

统计学更像是在问：

> 有没有一个公式，可以直接把最优参数算出来？

因此重点在于：

* 推导
* 证明
* 参数估计
* 理论性质

---

### 机器学习：SGD（Stochastic Gradient Descent）

机器学习通常把问题写成：

$$
\hat y = w^Tx+b
$$

首先定义损失函数：

$$
MSE =
\frac{1}{n}
\sum_{i=1}^{n}
(y_i-\hat{y}_i)^2
$$

目标：

$$
\min_{w,b} MSE
$$

与统计学不同，机器学习通常不会直接求解析解，而是通过不断更新参数逐步逼近最优解。

参数更新规则：

$$
w
\leftarrow
w-\eta \nabla_w L
$$

其中：

* $L$ 为损失函数
* $\nabla_w L$ 为梯度
* $\eta$ 为学习率（Learning Rate）

不断重复：

1. 计算预测值
2. 计算损失
3. 计算梯度
4. 更新参数

直到收敛。

---

#### SGD 的思维方式

机器学习更像是在问：

> 如果算不出答案，我能不能一步一步逼近答案？

因此重点在于：

* Optimization
* Gradient
* Iteration
* Scalability

---

### 两种方法的区别

| OLS     | SGD      |
| ------- | -------- |
| 统计学经典方法 | 机器学习经典方法 |
| 直接求解    | 迭代求解     |
| 得到解析解   | 得到数值解    |
| 适合小规模问题 | 适合大规模问题  |
| 关注估计性质  | 关注优化过程   |
| 需要矩阵求逆  | 不需要矩阵求逆  |

---

### 我的理解

OLS 像是在解一道数学题：

> 直接推导出正确答案。

SGD 像是在下山找最低点：

> 不知道答案在哪，但知道每一步该往哪里走。

两者最终寻找的都是最优参数，只是寻找的方法不同。


In [9]:
import numpy as np

# 计算损失函数
def compute_cost(X, y, theta):
    m = len(y)
    predictions = X.dot(theta)
    # 计算线性回归的损失函数
    cost = (1 / (2 * m)) * np.sum(np.square(predictions - y))
    return cost


def gradient_descent(X, y, theta, alpha, num_iters):
    m = len(y)
    J_history = np.zeros(num_iters)  

    for i in range(num_iters):
        predictions = X.dot(theta)
        error = predictions - y
        gradient = (1 / m) * X.T.dot(error)
        theta = theta - alpha * gradient
        J_history[i] = compute_cost(X, y, theta)

    return theta, J_history


def stochastic_gradient_descent(X, y, theta, alpha, num_iters):
    m = len(y)
    J_history = np.zeros(num_iters)

    for i in range(num_iters):
        perm = np.random.permutation(m)
        X_shuffle = X[perm]
        y_shuffle = y[perm]

        for j in range(m):
            xi = X_shuffle[j:j+1]
            yi = y_shuffle[j:j+1]
            pred = xi.dot(theta)
            err = pred - yi
            grad = xi.T.dot(err)
            theta = theta - alpha * grad

        J_history[i] = compute_cost(X, y, theta)
    return theta, J_history


if __name__ == '__main__':

    np.random.seed(0)
    X = 2 * np.random.rand(100, 1)
    y = 4 + 3 * X + np.random.randn(100, 1)
    X_b = np.c_[np.ones((100, 1)), X]
    alpha = 0.01      # 学习率
    num_iters = 1000  # 迭代总次数

    # ========== 1. 运行 BGD ==========
    np.random.seed(0)
    theta_bgd = np.random.randn(2, 1)
    theta_bgd, cost_bgd = gradient_descent(X_b, y, theta_bgd, alpha, num_iters)

    print("--- 线性回归（BGD批量梯度下降）---")
    print("优化后的参数 (theta):")
    print(theta_bgd)

    # ========== 2. 运行 SGD ==========
    np.random.seed(0)
    theta_sgd = np.random.randn(2, 1)
    theta_sgd, cost_sgd = stochastic_gradient_descent(X_b, y, theta_sgd, alpha, num_iters)

    print("\n--- 线性回归（SGD随机梯度下降）---")
    print("优化后的参数 (theta):")
    print(theta_sgd)

--- 线性回归（BGD批量梯度下降）---
优化后的参数 (theta):
[[4.2021311 ]
 [2.98623183]]

--- 线性回归（SGD随机梯度下降）---
优化后的参数 (theta):
[[4.21016078]
 [2.94527777]]


In [11]:
import numpy as np
from sklearn.linear_model import LinearRegression, SGDRegressor

np.random.seed(0)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

lr = LinearRegression()
lr.fit(X, y)

print("===== Sklearn OLS 最小二乘 (解析解，等价完美BGD) =====")
print(f"截距 θ0: {lr.intercept_[0]:.4f}")
print(f"斜率 θ1: {lr.coef_[0][0]:.4f}")
print(f"完整theta向量：\n{np.array([[lr.intercept_[0]], [lr.coef_[0][0]]])}\n")


sgd_reg = SGDRegressor(
    loss="squared_error",  # 损失：均方误差，和我们手写一致
    learning_rate="constant",
    eta0=0.01,             # 学习率 alpha=0.01
    max_iter=1000,         # 迭代次数
    random_state=0,        # 固定随机种子复现
    fit_intercept=True     # 自动添加偏置项θ0
)

sgd_reg.fit(X, y.ravel())

print("===== Sklearn SGDRegressor 随机梯度下降 =====")
print(f"截距 θ0: {sgd_reg.intercept_[0]:.4f}")
print(f"斜率 θ1: {sgd_reg.coef_[0]:.4f}")
print(f"完整theta向量：\n{np.array([[sgd_reg.intercept_[0]], [sgd_reg.coef_[0]]])}")

===== Sklearn OLS 最小二乘 (解析解，等价完美BGD) =====
截距 θ0: 4.2222
斜率 θ1: 2.9685
完整theta向量：
[[4.22215108]
 [2.96846751]]

===== Sklearn SGDRegressor 随机梯度下降 =====
截距 θ0: 4.1693
斜率 θ1: 3.0241
完整theta向量：
[[4.16934313]
 [3.02407045]]
